version: "3.9"
services: 
  backend:
    tty: true
    image: node:10
    container_name: back-container-image.io
    restart: always
    working_dir: /app
    command: npm start
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api:/app
      - ./log/nginx/backend:/var/log/nginx
  
  frontend:
    image: ubuntu/nginx
    container_name: frontend-container-image.io
    restart: always
    working_dir: /app
    ports:
      - "5051:5051"
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./front/dist:/app
      - ./log/nginx/frontend:/var/log/nginx
    links:
      - backend
